export declare enum ImreadModes {
    IMREAD_UNCHANGED = -1,
    IMREAD_GRAYSCALE = 0,
    IMREAD_COLOR_BGR = 1,
    IMREAD_COLOR = 1,
    IMREAD_ANYDEPTH = 2,
    IMREAD_ANYCOLOR = 4,
    IMREAD_LOAD_GDAL = 8,
    IMREAD_REDUCED_GRAYSCALE_2 = 16,
    IMREAD_REDUCED_COLOR_2 = 17,
    IMREAD_REDUCED_GRAYSCALE_4 = 32,
    IMREAD_REDUCED_COLOR_4 = 33,
    IMREAD_REDUCED_GRAYSCALE_8 = 64,
    IMREAD_REDUCED_COLOR_8 = 65,
    IMREAD_IGNORE_ORIENTATION = 128,
    IMREAD_COLOR_RGB = 256
}
export declare enum ImwriteEXRCompressionFlags {
    IMWRITE_EXR_COMPRESSION_NO = 0,
    IMWRITE_EXR_COMPRESSION_RLE = 1,
    IMWRITE_EXR_COMPRESSION_ZIPS = 2,
    IMWRITE_EXR_COMPRESSION_ZIP = 3,
    IMWRITE_EXR_COMPRESSION_PIZ = 4,
    IMWRITE_EXR_COMPRESSION_PXR24 = 5,
    IMWRITE_EXR_COMPRESSION_B44 = 6,
    IMWRITE_EXR_COMPRESSION_B44A = 7,
    IMWRITE_EXR_COMPRESSION_DWAA = 8,
    IMWRITE_EXR_COMPRESSION_DWAB = 9
}
export declare enum ImwriteEXRTypeFlags {
    IMWRITE_EXR_TYPE_HALF = 1,
    IMWRITE_EXR_TYPE_FLOAT = 2
}
export declare enum ImwriteFlags {
    IMWRITE_JPEG_QUALITY = 1,
    IMWRITE_JPEG_PROGRESSIVE = 2,
    IMWRITE_JPEG_OPTIMIZE = 3,
    IMWRITE_JPEG_RST_INTERVAL = 4,
    IMWRITE_JPEG_LUMA_QUALITY = 5,
    IMWRITE_JPEG_CHROMA_QUALITY = 6,
    IMWRITE_JPEG_SAMPLING_FACTOR = 7,
    IMWRITE_PNG_COMPRESSION = 16,
    IMWRITE_PNG_STRATEGY = 17,
    IMWRITE_PNG_BILEVEL = 18,
    IMWRITE_PXM_BINARY = 32,
    IMWRITE_EXR_TYPE = 48,
    IMWRITE_EXR_COMPRESSION = 49,
    IMWRITE_EXR_DWA_COMPRESSION_LEVEL = 50,
    IMWRITE_WEBP_QUALITY = 64,
    IMWRITE_HDR_COMPRESSION = 80,
    IMWRITE_PAM_TUPLETYPE = 128,
    IMWRITE_TIFF_RESUNIT = 256,
    IMWRITE_TIFF_XDPI = 257,
    IMWRITE_TIFF_YDPI = 258,
    IMWRITE_TIFF_COMPRESSION = 259,
    IMWRITE_TIFF_ROWSPERSTRIP = 278,
    IMWRITE_TIFF_PREDICTOR = 317,
    IMWRITE_JPEG2000_COMPRESSION_X1000 = 272,
    IMWRITE_AVIF_QUALITY = 512,
    IMWRITE_AVIF_DEPTH = 513,
    IMWRITE_AVIF_SPEED = 514,
    IMWRITE_JPEGXL_QUALITY = 640,
    IMWRITE_JPEGXL_EFFORT = 641,
    IMWRITE_JPEGXL_DISTANCE = 642,
    IMWRITE_JPEGXL_DECODING_SPEED = 643,
    IMWRITE_GIF_LOOP = 1024,
    IMWRITE_GIF_SPEED = 1025,
    IMWRITE_GIF_QUALITY = 1026,
    IMWRITE_GIF_DITHER = 1027,
    IMWRITE_GIF_TRANSPARENCY = 1028,
    IMWRITE_GIF_COLORTABLE = 1029
}
export declare enum ImwriteGIFCompressionFlags {
    IMWRITE_GIF_FAST_NO_DITHER = 1,
    IMWRITE_GIF_FAST_FLOYD_DITHER = 2,
    IMWRITE_GIF_COLORTABLE_SIZE_8 = 3,
    IMWRITE_GIF_COLORTABLE_SIZE_16 = 4,
    IMWRITE_GIF_COLORTABLE_SIZE_32 = 5,
    IMWRITE_GIF_COLORTABLE_SIZE_64 = 6,
    IMWRITE_GIF_COLORTABLE_SIZE_128 = 7,
    IMWRITE_GIF_COLORTABLE_SIZE_256 = 8
}
export declare enum ImwriteHDRCompressionFlags {
    IMWRITE_HDR_COMPRESSION_NONE = 0,
    IMWRITE_HDR_COMPRESSION_RLE = 1
}
export declare enum ImwriteJPEGSamplingFactorParams {
    IMWRITE_JPEG_SAMPLING_FACTOR_411 = 4264209,
    IMWRITE_JPEG_SAMPLING_FACTOR_420 = 2232593,
    IMWRITE_JPEG_SAMPLING_FACTOR_422 = 2167057,
    IMWRITE_JPEG_SAMPLING_FACTOR_440 = 1184017,
    IMWRITE_JPEG_SAMPLING_FACTOR_444 = 1118481
}
export declare enum ImwritePAMFlags {
    IMWRITE_PAM_FORMAT_NULL = 0,
    IMWRITE_PAM_FORMAT_BLACKANDWHITE = 1,
    IMWRITE_PAM_FORMAT_GRAYSCALE = 2,
    IMWRITE_PAM_FORMAT_GRAYSCALE_ALPHA = 3,
    IMWRITE_PAM_FORMAT_RGB = 4,
    IMWRITE_PAM_FORMAT_RGB_ALPHA = 5
}
export declare enum ImwritePNGFlags {
    IMWRITE_PNG_STRATEGY_DEFAULT = 0,
    IMWRITE_PNG_STRATEGY_FILTERED = 1,
    IMWRITE_PNG_STRATEGY_HUFFMAN_ONLY = 2,
    IMWRITE_PNG_STRATEGY_RLE = 3,
    IMWRITE_PNG_STRATEGY_FIXED = 4
}
export declare enum ImwriteTiffCompressionFlags {
    IMWRITE_TIFF_COMPRESSION_NONE = 1,
    IMWRITE_TIFF_COMPRESSION_CCITTRLE = 2,
    IMWRITE_TIFF_COMPRESSION_CCITTFAX3 = 3,
    IMWRITE_TIFF_COMPRESSION_CCITT_T4 = 3,
    IMWRITE_TIFF_COMPRESSION_CCITTFAX4 = 4,
    IMWRITE_TIFF_COMPRESSION_CCITT_T6 = 4,
    IMWRITE_TIFF_COMPRESSION_LZW = 5,
    IMWRITE_TIFF_COMPRESSION_OJPEG = 6,
    IMWRITE_TIFF_COMPRESSION_JPEG = 7,
    IMWRITE_TIFF_COMPRESSION_T85 = 9,
    IMWRITE_TIFF_COMPRESSION_T43 = 10,
    IMWRITE_TIFF_COMPRESSION_NEXT = 32766,
    IMWRITE_TIFF_COMPRESSION_CCITTRLEW = 32771,
    IMWRITE_TIFF_COMPRESSION_PACKBITS = 32773,
    IMWRITE_TIFF_COMPRESSION_THUNDERSCAN = 32809,
    IMWRITE_TIFF_COMPRESSION_IT8CTPAD = 32895,
    IMWRITE_TIFF_COMPRESSION_IT8LW = 32896,
    IMWRITE_TIFF_COMPRESSION_IT8MP = 32897,
    IMWRITE_TIFF_COMPRESSION_IT8BL = 32898,
    IMWRITE_TIFF_COMPRESSION_PIXARFILM = 32908,
    IMWRITE_TIFF_COMPRESSION_PIXARLOG = 32909,
    IMWRITE_TIFF_COMPRESSION_DEFLATE = 32946,
    IMWRITE_TIFF_COMPRESSION_ADOBE_DEFLATE = 8,
    IMWRITE_TIFF_COMPRESSION_DCS = 32947,
    IMWRITE_TIFF_COMPRESSION_JBIG = 34661,
    IMWRITE_TIFF_COMPRESSION_SGILOG = 34676,
    IMWRITE_TIFF_COMPRESSION_SGILOG24 = 34677,
    IMWRITE_TIFF_COMPRESSION_JP2000 = 34712,
    IMWRITE_TIFF_COMPRESSION_LERC = 34887,
    IMWRITE_TIFF_COMPRESSION_LZMA = 34925,
    IMWRITE_TIFF_COMPRESSION_ZSTD = 50000,
    IMWRITE_TIFF_COMPRESSION_WEBP = 50001,
    IMWRITE_TIFF_COMPRESSION_JXL = 50002
}
export declare enum ImwriteTiffPredictorFlags {
    IMWRITE_TIFF_PREDICTOR_NONE = 1,
    IMWRITE_TIFF_PREDICTOR_HORIZONTAL = 2,
    IMWRITE_TIFF_PREDICTOR_FLOATINGPOINT = 3
}
