excluded_modules = [
    "calib3d",
    "dnn",
    #"flann",
    "gapi",
    "highgui",
    #"java",
    "js",
    "ml",
    "objc",
    "objdetect",
    "python",
    #"stitching",
    "ts",
    "video",
    "world",
    "dpm",
    "face",
    "fuzzy",
    "hdf",
    "line_descriptor",
    "matlab",
    "plot",
    "reg",
    "rgbd",
    "saliency",
    "sfm",
    "stereo",
    "text",
    "xphoto",
    "surface_matching",
    "photo",
    "cudaarithm",
    "cudabgsegm",
    "cudacodec",
    "viz",
    "cudastereo",
    "datasets",
    "cudafeatures2d",
    "cudafilters",
    "cudaimgproc",
    "cudalegacy",
    "cudaobjdetect",
    "cudaoptflow",
    "cudawarping",
    "cudev",
    "shape",
    "superres",
    "videostab",
    "ccalib",
    "structured_light",
    "tracking",
    "aruco",
    "bgsegm",
    "cvv",
]
excluded_dict = {f"BUILD_opencv_{x}": "OFF" for x in excluded_modules}

cmake_common_vars = dict(excluded_dict, )

ABIs = [
    ABI(
        "2",
        "armeabi-v7a",
        None,
        cmake_vars=dict(cmake_common_vars, ANDROID_ABI="armeabi-v7a with NEON"),
    ),
    ABI(
        "3",
        "arm64-v8a",
        None,
        cmake_vars=dict(cmake_common_vars, ANDROID_SUPPORT_FLEXIBLE_PAGE_SIZES="ON"),
    ),
    ABI(
        "5",
        "x86_64",
        None,
        cmake_vars=dict(cmake_common_vars, ANDROID_SUPPORT_FLEXIBLE_PAGE_SIZES="ON"),
    ),
    #ABI("4", "x86", None, cmake_vars=dict(cmake_common_vars, ANDROID_SUPPORT_FLEXIBLE_PAGE_SIZES="ON")),
]
